const routes = {    
    //Menu principal
    HOME:'/',
    CURSOS_CAPACITACION:'/cursos-capacitacion',
    ABOUT:'/taec',
    PARTNERS:'/taec#Nuestros-Partners',
    TIENDA:'https://tienda.taec.com.mx/',
    CONTACTO:'/contacto',
    SOPORTE:'/soporte-tecnico',
    //Menu desplegable (SERVICIOS)
    SEVEN_MINUTES:'/7minutes',
    CURSOS_CATALOGO:'/cursos-catalogo',
    DESARROLLO_CURSOS:'/desarrollo-cursos',
    HERRAMIENTAS_AUTORIA:'/herramientas-autoria',
    PLATAFORMAS_ELEARNING:'/plataformas-elearning',
    EXTENCIONES_APRENDIZAJE:'/extensiones-aprendizaje',
    SERVICIOS_TI:'/servicios-ti',
    EXAMENES:'/examenes',
    IMPLEMENTAR_ELEARNING:'/contacto',
    //Cursos de capacitación
    CC_ARTICULATE_ASSISTANT:'/cursos-capacitacion#Articulate-Assistant',
    CC_ARTICULATE360:'/cursos-capacitacion#Articulate-360',
    CC_D_ELEARNING:'/cursos-capacitacion#Diseño-elearning',
    CC_C_ACCESIBLES_ARTICULATE360:'/cursos-capacitacion#cursos-accesibles-Articulate-360',
    CC_STORYLINE_AVANZADO:'/cursos-capacitacion#Storyline-Avanzado',
    CC_D_INSTRUCCIONAL:'/cursos-capacitacion#Diseño-Instruccional',
    CC_MOODLE:'/cursos-capacitacion#Moodle',
    CC_TOTARA:'/cursos-capacitacion#Totara',
    CC_VYOND:'/cursos-capacitacion#Vyond',
    //Herramientas de autoria
    H_AUTORIA:'/herramientas-autoria',
    STORYLINE_360:'/storyline-360',
    RISE_360:'/rise-360',
    CONTENT_LIBRARY:'/content-library',
    REVIEW_360:'/review-360',
    PEEK_360:'/peek-360',
    STUDIO_360:'/studio-360',
    REPLAY_360:'/replay-360',
    ARTICULATE_TRAINING:'/articulate-training',
    AI_ASSISTANT:'/ai-assistant',
    VYOND:'/vyond',
    ARTICULATE_360:'/articulate-360',
    //Desarrollo de cursos a la medida
    ELEARNING:'/desarrollo-cursos',
    MICROLEARNING:'/desarrollo-cursos#Microlearning',
    BLENDED_LEARNIGN:'/desarrollo-cursos#Blended-Learning',
    MOOCS:'/desarrollo-cursos#Moocs',
    ADAPTIVE_LEARNING:'/desarrollo-cursos#Adaptive-Learning',
    //Cursos de catalogo
    LEARNING_COFFEE:'/cursos-catalogo#Learning-Coffee',
    GO1:'/cursos-catalogo#Go-one',
    CUSTOM_GUIDE:'/cursos-catalogo#Custom-Guide',
    //Plataformas elearning
    MOODLE:'/moodle',
    TOTARA:'/totara', 
    TOTARA_LEARN: '/totara-learn',
    TOTARA_ENGAGE: '/totara-engage',
    TOTARA_PERFORM: '/totara-perform',
    OTTOLEARN:'/ottolearn',
    REACH_360:'/reach-360',
    ONE_NEO:'/one',
    LYS:'/lys',
    //Extensiones de aprendizaje
    MOTRAIN:'/motrain',
    CLASS:'/class',
    BBB:'/bigbluebutton',    
    AUTOCERT:'/autocert',
    ZOOLA:'/zoola',
    //Exámenes de alta seguridad
    SARAS:'/saras',
    EVALUACIONES:'/evaluaciones',
    //Slider Partners
    PARTNER_ARTICULATE:'https://www.articulate.com',
    PARTNER_TOTARA:'https://www.totara.com/es',
    PARTNERS_EXCELSOFT:'https://www.excelsoftcorp.com',
    PARTNER_EDIFICE:'https://edifice.io',
    PARTNER_MOTRAIN:'https://motrain.com',
    PARTNER_LAMBDA:'https://www.lambdasolutions.net',    
    PARTNER_AVILAR:'https://www.avilar.com/index.html',
    PARTNER_VYOND:'https://www.vyond.com',
    PARTNER_OTTOLEARN:'https://www.ottolearn.com',
    PARTNER_EXACT:'https://www.exactls.com',
    PARTNER_BELATRIX:'https://www.belatrix.com',
    PARTNER_GO1:'https://www.go1.com',
    PARTNER_BEYOND:'https://beyondtalentmanagement.com',
    PARTNER_LEARNMEXICO:'https://www.learnmexico.com',
    PARTNER_NETEX:'https://www.netexlearning.com',
    //Contacto y soporte
    UBICACION:'/contacto#Ubicacion',
    BOLSA_TRABAJO:'/contacto#Bolsa-trabajo',
    //TAEC Store
    STORE_ARTICULATE360P:'https://tienda.taec.com.mx/1',
    STORE_ARTICULATE360T:'https://tienda.taec.com.mx/3', 
    STORE_TOTARA:'https://tienda.taec.com.mx/22',
    STORE_VYONDPRE:'https://tienda.taec.com.mx/5',
    STORE_VYONDPRO:'https://tienda.taec.com.mx/6',
    STORE_MOODLE:'https://tienda.taec.com.mx/?produc=moodle',
    STORE_ART_AI: 'https://tienda.taec.com.mx/descarticuser/111',
    STORE_ART_360_AI: 'https://tienda.taec.com.mx/103',
    STORE_CURSOS_ARTICULATE:'https://tienda.taec.com.mx/?descrip=Cursos',
    STORE_DIS_ELEARNING:'https://tienda.taec.com.mx/25',
    STORE_CURSOS_ARTICULATE_ACCESIBLE:'https://tienda.taec.com.mx/100',
    STORE_CURSOS_VYOND:'https://tienda.taec.com.mx/24',
    STORE_CURSOS_TOTARA:'https://tienda.taec.com.mx/22',
    // Calendarios
    CALENDARIO:'/calendario',
    CALENDARIO_ART_360:'/calendario#Articulate-360',
    CALENDARIO_ART_AI:'/calendario#Articulate-Assistant',
    CALENDARIO_DIS_ELE:'/calendario#Diseño-elearning',
    CALENDARIO_ART_ACC:'/calendario#cursos-accesibles-Articulate-360',
    CALENDARIO_STO_AVA:'/calendario#Storyline-Avanzado',
    CALENDARIO_DIS_INS:'/calendario#Diseño-Instruccional',
    CALENDARIO_VYO:'/calendario#Vyond',
    CALENDARIO_MOO:'/calendario#Moodle',
    // Demos
    DEMO_LYS:'https://www.lys.academy/demoslys/taec',
    //Landigs pages
    LAND_SEVEN_MINUTES:'/landing/7',
    //Terminos y condiciones
    TERMINOS_CONDICIONES:'/terminos-y-condiciones',
    PRIVACIDAD:'/privacidad',
    POLITICAS:'/politicas',
    /*Auth*/
    LOGIN:'/login',
    REGISTER:'/register',
    FORGOT_PASSWORD:'/forgot-password',
    RESET_PASSWORD:'/reset-password',
    /*admin*/
    PAGE_ADMIN:'/page-admin',
    /*redes sociales*/
    FACEBOOK:'https://www.facebook.com/TAEC.eLearning/',    
    LINKEDIN:'https://www.linkedin.com/company/3218246/admin/',
    BLOG:'https://blog.taec.com.mx/',
    YOUTUBE:'https://www.youtube.com/channel/UCHQvrBBESK9JPJqxJW8DVgQ/',
    WHATSAPP:'https://wa.me/5527758279',
    /*otras*/
    UNAUTHORIZED:'/unauthorized',
    CANCELAR:'/',
    HELLOWORLD:'/helloworld',
    // Paginas Administrador
    DASHBOARD:'/dashboard',
    WELCOME:'/dashboard/welcome',
    LIST_CUSTOMERS: "/dashboard/list-customers",
    CREATE_USERS: "/dashboard/create-user",
    LIST_USERS: "/dashboard/list-users",
    EDIT_USER:'/dashboard/edit-user',
    ADMINS:'/dashboard/admins',
    CREATE_AREAS:'/dashboard/create-area',
    LIST_AREAS:'/dashboard/list-areas',
    EDIT_AREA:'/dashboard/edit-area',
    ASSIGN_AREA_USER:'/dashboard/assign-area-to-user',
    UNASSIGN_AREA_USER: "/dashboard/unassign-area-to-user",
};

export default routes;